swagger: '2.0'

info:
  title: GS CloudRun CF Endpoints - dev
  version: 1.0.0

host: gs-cloudrun-cf-r2c3tge7oq-uc.a.run.app

schemes:
  - https

produces:
  - application/json

paths:
  "/graphql":
    get:
      description: "GraphQL GET endpoint"
      operationId: "getGraphql"
      consumes:
        - "application/graphql"
      produces:
        - "application/json"
      responses:
        200:
          description: "GraphQL GET queries endpoint"
      x-google-backend:
        address: https://us-central1-dev-gs-platform.cloudfunctions.net/getGraphql
    post:
      description: "GraphQL POST endpoint"
      operationId: "postGraphql"
      consumes:
        - "application/graphql"
      produces:
        - "application/json"
      responses:
        200:
          description: "GraphQL POST queries endpoint"
      x-google-backend:
        address: https://us-central1-dev-gs-platform.cloudfunctions.net/postGraphql

security:
  - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "header"
